import numpy as np


# for simulation
SCENARIO_ID = 1
LOAD_DATA = False
INIT_STATE = np.array([0.0, 0.0, 10.0, 0.0, 0.0, 3.0, 1.5])
MEAS_COV = np.diag([1.0, 1.0])**2
SIGMA_OR = np.sqrt(0.01*np.pi) if SCENARIO_ID == 0 else np.sqrt(0.2*np.pi)
SIGMA_V1 = 0.1
SIGMA_V2 = 0.1

TIME_STEPS = 17  # number of time steps
TD = 1.0  # time difference between steps
GT_POIS = 5  # poisson rate of measurements generated by ground truth
RUNS = 1#000

# for plotting
AX_LIMS = [-10, 160, -10, 160]

# for tracking
INIT_STATE_COV = np.diag([0.5, 0.5, 0.1, 0.1, np.sqrt(0.5*np.pi), 0.2, 0.1])**2
AX_MIN = 0.1  # minimum semi-axis length

# MEM-EKF*
MEM_H = np.array([
    [1.0, 0.0, 0.0, 0.0],
    [0.0, 1.0, 0.0, 0.0],
])
MEM_KIN_DYM = np.array([
    [1.0, 0.0, TD,  0.0],
    [0.0, 1.0, 0.0,  TD],
    [0.0, 0.0, 1.0, 0.0],
    [0.0, 0.0, 0.0, 1.0],
])
MEM_SHAPE_DYM = np.identity(3)

# indices for ground truth and estimate
X1 = 0
X2 = 1
V1 = 2
V2 = 3
AL = 4
L = 5
W = 6
